---
abstract: unknown
author:
  - 'aaron trevena <teejay@droogs.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SOAP-Data-Builder
no_index:
  directory:
    - t
    - inc
requires:
  SOAP::Lite: 0.65
version: 1
